image: buildpack-deps:18.04-scm

job:
  only:
    refs:
      - gitlab
      - standalone
  parallel: 4

  before_script:
    - ./fix-hosts.sh && TESTSPACE_URL=$(cat testspace-url)
    - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C /usr/local/bin
    - |
      if [ "${QA_DOMAIN}" == "s2.test.stridespace.com" ]; then 
        export TESTSPACE_TOKEN=s2-admin:s2-admin
      fi
    - testspace config url $TESTSPACE_URL
    - testspace -v
    - printenv
  
  script:
    - echo script
  
  after_script:
    - |
      case "$CI_COMMIT_MESSAGE" in
        *s2.test.stridespace.com*) export TESTSPACE_TOKEN=s2-admin:s2-admin ;;
      esac
    - |
      for ((i=$CI_NODE_INDEX; i<=10; i=i+$CI_NODE_TOTAL))
      do
        export JOB=JOB-$i
        ./ts-time-push.sh
      done
