image: buildpack-deps:18.04-scm

job:
  only:
    refs:
      - standalone
  
  before_script:
    - ./fix-hosts.sh && TESTSPACE_URL=$(cat testspace-url)
    - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C /usr/local/bin
    - testspace config url "$TESTSPACE_URL/s2technologies:testspace.test.ci"
    - testspace -v
  
  script:
    - printenv > printenv.txt
  
  after_script:
    - |
      if [[ ${CI_COMMIT_TITLE} == *"s2.test.stridespace.com"* ]]; then 
        export TESTSPACE_TOKEN=s2-admin:s2-admin
      fi
    - testspace results.xml printenv.txt "standalone#gitlab.$CI_PIPELINE_ID" --repo=git --build-url=$CI_PIPELINE_URL
