language: generic

branches:
  only:
  - standalone
  - travis

before_install:
  # Setup a wildcard local DNS for *.dev
  - QA_IP_URL=$(< commit-trigger.txt)
  - export QA_IP=${QA_IP_URL% *}
  - export QA_URL=${QA_IP_URL#* }
  - export QA_DOMAIN=${QA_URL#http://}
  - sudo apt-get install -qq -y --force-yes dnsmasq
  - echo "listen-address=127.0.0.1" | sudo tee -a /etc/dnsmasq.conf > /dev/null 2>&1
  - echo "bind-interfaces" | sudo tee -a /etc/dnsmasq.conf > /dev/null 2>&1
  - echo "address=/$QA_DOMAIN/$QA_IP" | sudo tee -a /etc/dnsmasq.conf > /dev/null 2>&1
  - echo "user=root" | sudo tee -a /etc/dnsmasq.conf > /dev/null 2>&1
  - sudo service dnsmasq restart
  - mkdir -p $HOME/bin
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url $QA_URL
  - testspace -v

env:
  matrix:
   - JOB=JOB-1
   - JOB=JOB-2
   - JOB=JOB-3
   - JOB=JOB-4
   - JOB=JOB-5
   - JOB=JOB-6
   - JOB=JOB-7
   - JOB=JOB-8
   - JOB=JOB-9
   - JOB=JOB-10

script:
  - echo script

after_script:
  - ./ts-time-push.sh
