language: generic

before_install:
  - mkdir -p $HOME/bin
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url http://$TS_TOKEN:@s2.stridespace.com/s2technologies:testspace.test.ci
  - testspace -v

script:
  - printenv > printenv.txt
 
after_script:
  - testspace results.xml printenv.txt "standalone#travis.$TRAVIS_BUILD_NUMBER" --repo git
