version: 1.0.{build}
configuration: Release

install:
  - appveyor DownloadFile https://testspace-client.s3.amazonaws.com/testspace-windows-dev.zip
  - 7z x -y testspace-windows-dev.zip
  - testspace config url http://%TS_TOKEN%:@s2.stridespace.com/s2technologies:testspace.test.ci
  - testspace -v

# to run your custom scripts instead of automatic MSBuild
build_script:
  - echo build script
  
# to run your custom scripts instead of automatic tests
test_script:
  - set > printenv.txt 
  
after_test:
  - testspace results.xml printenv.txt "standalone#appveyor.%APPVEYOR_BUILD_NUMBER%" --repo git