version: 1.0.{build}
configuration: Release

hosts:
  s2.stridespace.net: 54.202.81.91

branches:
  only:
    - standalone
    - appveyor

install:
  - appveyor DownloadFile https://testspace-client.s3.amazonaws.com/testspace-windows-dev.zip
  - 7z x -y testspace-windows-dev.zip
  - testspace config url http://s2.stridespace.net
  - testspace -v
  
environment:
  matrix:
   - JOB: JOB-1
   - JOB: JOB-2
   - JOB: JOB-3
   - JOB: JOB-4
   - JOB: JOB-5
   - JOB: JOB-6
   - JOB: JOB-7
   - JOB: JOB-8
   - JOB: JOB-9
   - JOB: JOB-10
   - JOB: JOB-11
   - JOB: JOB-12
   - JOB: JOB-13
   - JOB: JOB-14
   - JOB: JOB-15
   - JOB: JOB-16
   - JOB: JOB-17
   - JOB: JOB-18
   - JOB: JOB-19
   - JOB: JOB-20
   
build_script:
  - echo build script
 
test_script:
  - sh: TIME_START=$(date +%s%3N)
  - testspace result*.xml [ALL]result*.xml [$JOB]result*.xml
  - sh: TIME_END=$(date +%s%3N)
  - sh: TIME_DIFF=$(( $TIME_END - $TIME_START ))
  - sh: echo "TIMING STATS:" > timing.log
  - sh: echo "  $JOB Upload time in milliseconds: $TIME_DIFF" >> timing.log
  - sh: echo "$JOB Upload time, $TIME_DIFF" > timing.csv
  - testspace [$JOB]"timing.log{timing.csv:Tracking Time for $JOB}"
  
after_test:
