trigger:
- master
- standalone

pool: Default

steps:
- script: |
    sudo pip install pytest
    py.test generate-results.py --junitxml=results.xml -v --tb=no
  displayName: 'pytest'

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_qause'
    repositoryName: 'QAtest-Inc/testspace.test.ci'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    isDraft: true
    isPreRelease: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'