trigger:
- master
- standalone

pool: Default

steps:
- script: |
    python -m pip install --upgrade pip
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    py.test generate-results.py --junitxml=results.xml -v --tb=no
  displayName: 'pytest'




- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      sudo pip install pytest
      py.test generate-results.py --junitxml=results.xml -v --tb=no
