version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04-scm
    branches:
      only:
        - standalone
        - circle
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install and configure Testspace client
          command: |
            QA_IP_URL=$(< commit-trigger.txt)
            export QA_IP=${QA_IP_URL% *}
            export QA_URL=${QA_IP_URL#* }
            export QA_DOMAIN=${QA_URL#http://}
            echo $QA_IP $QA_DOMAIN | sudo tee -a /etc/hosts
            curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | sudo tar -zxvf- -C /usr/local/bin
            testspace config url $QA_URL
            testspace -v
            printenv
      - run:
          name: Push to Testspace server
          command: |
            for ((i=$CIRCLE_NODE_INDEX+1; i<=10; i=i+$CIRCLE_NODE_TOTAL))
            do
              export JOB=JOB-$i
              ./ts-time-push.sh
            done
          when: always
