version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04-scm
    branches:
      only:
        - standalone
        - circle
    steps:
      - checkout
      - run:
          name: Install and configure Testspace client
          command: |
            QA_IP_URL=$(< commit-trigger.txt)
            export QA_IP=${QA_IP_URL% *}
            export QA_URL=${QA_IP_URL#* }
            export QA_DOMAIN=${QA_URL#http://}
            echo $QA_IP $QA_DOMAIN | sudo tee -a /etc/hosts
            curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | sudo tar -zxvf- -C /usr/local/bin
            testspace config url "$QA_URL/s2technologies:testspace.test.ci"
            testspace -v
      - run:
          name: Get environment details
          command: printenv > printenv.txt
      - run:
          name: Push environment details to result
          command: testspace results.xml printenv.txt "standalone#circle.$CIRCLE_BUILD_NUM" --repo=git --build-url=$CIRCLE_BUILD_URL
          env: # temporary until Actions "build-bot" server support provided
            TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}