name: Default
on:
  push:
    branches:
      - standalone

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install and configure Testspace client
        run: |
          ./fix-hosts.sh && TESTSPACE_URL=$(cat testspace-url)
          curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | sudo tar -zxvf- -C /usr/local/bin
          testspace config url "$TESTSPACE_URL/s2technologies:testspace.test.ci"
          testspace -v
      - name: Get environment details
        run: printenv > printenv.txt
      - name: Push environment details to result
        run: |
          build_url="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}";
          echo $build_url
          # CI_COMMIT_MESSAGE=`jq -r ".commits[-1].message" ${GITHUB_EVENT_PATH}`
          case "$CI_COMMIT_MESSAGE" in
            *s2.stridespace.com*) ;;
            *) export TESTSPACE_TOKEN=s2-admin:s2-admin ;;
          esac
          testspace results.xml printenv.txt "standalone#github.$GITHUB_RUN_NUMBER" --repo=git --build-url=$build_url
        if: always()
        env: # temporary until GH Actions "build-bot" server support provided
          TESTSPACE_TOKEN: ${{ secrets.TESTSPACE_TOKEN }}
          CI_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
